"""
Signal 1: LLM-based classification via Groq.

Sends text to llama-3.3-70b-versatile and asks it to assess whether the
writing is AI-generated or human-written. Returns a float 0–1 where
1 = confident AI, 0 = confident human.

Blind spot: unreliable on texts < ~50 words; may under-flag heavily
human-edited AI output; may over-flag formal human writing (legal/academic).
"""

import json
import os

from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


_SYSTEM_PROMPT = """\
You are an expert at detecting whether text was written by a human or generated by an AI.

Analyze the provided text and return a JSON object with exactly two fields:
- "ai_probability": a float between 0.0 and 1.0 where 1.0 means you are certain the text is AI-generated and 0.0 means you are certain it is human-written.
- "reasoning": a brief (1-2 sentence) explanation of the key indicators that led to your score.

Consider indicators such as: unusual uniformity, hedged/over-balanced phrasing, unnaturally smooth transitions, absence of personal voice or idiosyncrasy, overly comprehensive enumeration of points, and lack of genuine opinion.

Respond with only the JSON object, no markdown fences."""


def score(text: str) -> float:
    """Return a 0-1 AI probability score for the given text using Groq."""
    client = _get_client()
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Text to analyze:\n\n{text}"},
        ],
        temperature=0.1,
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown fences if the model added them despite instructions
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    data = json.loads(raw)
    prob = float(data["ai_probability"])
    return max(0.0, min(1.0, prob))
